# azure-pipelines.yml
trigger:
  tags:
    include:
    - 'v*'
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  CI: true

steps:
  - bash: |
      echo "Build $(Build.SourceBranch)"
      RELEASE_REGEX="v[0-9](.[0-9]+){3}"
      tagName=${BUILD_SOURCEBRANCH#refs/tags/}
      if [[ "$(Build.SourceBranch)" =~ $RELEASE_REGEX ]] 
      then
       echo "##vso[build.updatebuildnumber]$tagName"
       echo "##vso[build.addbuildtag]$tagName"
       echo "##vso[build.addbuildtag]Release"
      fi
    displayName: Tag Releases

  - task: qetza.replacetokens.replacetokens-task.replacetokens@6
    displayName: 'Replace tokens in **/appsettings.json'
    inputs:
      sources: '**/appsettings.json'

  - task: Bash@3
    enabled: true
    displayName: Install Docker
    inputs:
      targetType: inline
      script: >-
        sudo apt update
        sudo apt install apt-transport-https ca-certificates curl
        software-properties-common -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        sudo apt update
        apt-cache policy docker-ce
        sudo apt install docker-ce -y
        sudo systemctl start docker

  - task: Bash@3
    enabled: true
    displayName: Pulling Required Docker Images for SQL Server
    inputs:
      targetType: inline
      script: |-
        sudo docker stop sql1
        sudo docker rm sql1
        sudo docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=1Password" \
            -p 1433:1433 --name sql1 --hostname sql1 \
            -d \
            mcr.microsoft.com/mssql/server:2022-latest

  - task: Bash@3
    enabled: true
    displayName: Docker SQL Connection Test
    inputs:
      targetType: inline
      script: |
        CONTAINER_NAME="sql1"
        MAX_RETRIES=10
        RETRY_INTERVAL=5
        RETRY_COUNT=0
        while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
          container_status=$(sudo docker inspect -f '{{.State.Status}}' $CONTAINER_NAME)
          if [[ $container_status != "running" ]]; then
            echo "SQL Server container is not running. Retrying...(retry $RETRY_COUNT/$MAX_RETRIES)"
            sleep $RETRY_INTERVAL
            ((RETRY_COUNT++))
            continue
          fi
          if [[ "$(sudo docker logs $CONTAINER_NAME | grep 'SQL Server is now ready for client connections' | wc -l)" -eq 0 ]]; then
            echo "Waiting for SQL Server log entry stating its ready for connections...(retry $RETRY_COUNT/$MAX_RETRIES)"
            sleep $RETRY_INTERVAL
            ((RETRY_COUNT++))
          else
            echo "SQL Server container is ready!"
            break
          fi
        done
        if [[ $RETRY_COUNT -eq $MAX_RETRIES ]]; then
          echo "SQL Server container is not ready after $MAX_RETRIES retries"
          exit 1
        fi

  - task: UseDotNet@2
    displayName: "Install .NET Core SDK"
    inputs:
      version: 9.x
      performMultiLevelLookup: true
      includePreviewVersions: true

  - script: |
      echo "PATH: $PATH"
      dotnet --info
      dotnet --list-sdks
    displayName: 'Verify .NET SDKs'
    env:
      DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet
      PATH: $(Agent.ToolsDirectory)/dotnet:$(PATH)

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Restore"
    inputs:
      command: "restore"
      feedsToUse: "select"
      projects: "**/*.csproj"
      includeNuGetOrg: true
    env:
      DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet
      PATH: $(Agent.ToolsDirectory)/dotnet:$(PATH)

  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '24.x'

  - script: |
      dotnet --info
      npm ci
      npx playwright install --with-deps
      npx playwright test
    workingDirectory: './LondonDataServices.IDecide.Portal.Client'
    displayName: 'Playwright test'
    env:
      DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet
      PATH: $(Agent.ToolsDirectory)/dotnet:$(PATH)

  - task: Npm@1
    displayName: 'Install client dependencies (patient portal)'
    inputs:
      command: 'install'
      workingDir: 'LondonDataServices.IDecide.Portal.Client'
    env:
      DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet
      PATH: $(Agent.ToolsDirectory)/dotnet:$(PATH)

  - task: Npm@1
    displayName: 'Install client dependencies (back office portal)'
    inputs:
      command: 'install'
      workingDir: 'LondonDataServices.IDecide.Manage.Client'
    env:
      DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet
      PATH: $(Agent.ToolsDirectory)/dotnet:$(PATH)

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish Patient Portal"
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/LondonDataServices.IDecide.Portal.Server.csproj"
      arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_patient_portal"
      zipAfterPublish: true
      modifyOutputPath: false
    env:
      DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet
      PATH: $(Agent.ToolsDirectory)/dotnet:$(PATH)

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_patient_portal
    displayName: 'Publish Artifact - Patient Portal'
    artifact: drop-patient-portal

  - task: DotNetCoreCLI@2
    displayName: "Dotnet Publish Back Office Portal"
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/LondonDataServices.IDecide.Manage.Server.csproj"
      arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_backend_portal"
      zipAfterPublish: true
      modifyOutputPath: false
    env:
      DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet
      PATH: $(Agent.ToolsDirectory)/dotnet:$(PATH)

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_backend_portal
    displayName: 'Publish Artifact - Back Office'
    artifact: drop-backoffice-portal